version: 2.1

orbs:
  sonar: hubci/sonar@0.3

workflows:
  main:
    jobs:
      - build:
          context: main-context

jobs:
  build:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker Images"
          command: |
            # Fix hardcoded 'cimg' until CircleCI fixes this
            sed -i 's/cimg/hubci/g' build-images.sh
            sed -i 's/FROM cimg/FROM hubci/g' ./*/node/Dockerfile
            ./build-images.sh
      - sonar/install:
          version: 0.12.0
      - deploy:
          name: "Publish Docker Images (master branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              
              # an else block will be added in the future for a staging release
              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Publishing hubci/gotham to Docker Hub production."
                docker push hubci/gotham
              else
                echo "Skipping publishing."
              fi

              # Update the Docker Hub description
              sonar set description hubci/gotham ./README.md
            fi
